import './globals.css'
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'

const Ubuntus = Ubuntu({weight:["300","400","500","700"],subsets:["cyrillic"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Ubuntus.className}>{children}</body>
    </html>
  )
}
